name: Filip Syta
favicon: null
layout_spectrum: 0.7131081351544708
typography_spectrum: 0.29434241889975965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1831921620760113
  lightness: 0.8481695177033544
  saturation: 0.37140767253004014
  rhythmicContrast: 0.5559842826332897
purpose: []
